/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118081-g7b0bd6c4a7-20241217"
#endif /* AVUTIL_FFVERSION_H */
